name: Full Workflow
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  Discord-Begin:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{github.repository}}
          avatar-url: https://static.vecteezy.com/system/resources/previews/023/416/435/original/funny-avatar-of-a-character-with-one-eye-png.png
          embed-title: "Security Pipeline jobs are starting..."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"

  deploy:
    name: "Deploy to ITAS WMD server"
    runs-on: self-hosted
    steps:
      - name: Copy source code files
        uses: actions/checkout@master

      - name: Show files and start docker
        run: |
          whoami
          ls
          docker-compose up -d 
          docker ps

  SCA-Snyk:
    runs-on: ubuntu-latest
    needs: [trufflehog]
    steps:
      - uses: actions/checkout@v3
      - name: Build a Docker image
        run: docker build -t assignment1:latest .
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{secrets.SNYK_KEY}}
        with:
          image: assignment1:latest
          args: --file=Dockerfile --serif-file-output=snyk.sarif
      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-sca.sarif
          path: snyk.sarif
  Snyk-Report:
    runs-on: ubuntu-latest
    needs: [SCA-Snyk]
    steps:
      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{github.repository}}
          avatar-url: https://static.vecteezy.com/system/resources/previews/023/416/435/original/funny-avatar-of-a-character-with-one-eye-png.png
          embed-title: "Snyk SCA scan completed. Check the report for vulnerabilities."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"

  SAST-Semgrep:
    runs-on: ubuntu-latest
    needs: [trufflehog]
    container:
      image: returntocorp/semgrep

    steps:
      - name: clone application source code
        uses: actions/checkout@v3

      - name: full semgrep scan
        run: |
          semgrep \
          --sarif --output semgrep-sast.sarif \
          --metrics=off \
          --config="p/default"

      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-sast.sarif
          path: semgrep-sast.sarif

  Semgrep-Report:
    runs-on: ubuntu-latest
    needs: [SAST-Semgrep]
    steps:
      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{github.repository}}
          avatar-url: https://static.vecteezy.com/system/resources/previews/023/416/435/original/funny-avatar-of-a-character-with-one-eye-png.png
          embed-title: "Semgrep SAST scan completed. Check the report for vulnerabilities."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"

  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified

  build-and-push:
    runs-on: ubuntu-latest
    needs: [SCA-Snyk, SAST-Semgrep, trufflehog]
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/itas276owasp:latest

  discord-end:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{github.repository}}
          avatar-url: https://static.vecteezy.com/system/resources/previews/023/416/435/original/funny-avatar-of-a-character-with-one-eye-png.png
          embed-title: "Security Pipeline jobs are completed..."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"
