name: Full Workflow
# This workflow is triggered on push and pull request events to the master branch
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  # This job is triggered when the workflow starts and sends a notification to Discord
  Discord-Begin:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{github.repository}}
          avatar-url: https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/batman_hero_avatar_comics-512.png
          embed-title: "Security Pipeline jobs are starting..."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"
          thread-id: "1226943908676632756"

  # commented out as we are not deploying to ITAS WMD server for this example
  # deploy:
  #   name: "Deploy to ITAS WMD server"
  #   runs-on: self-hosted
  #   steps:
  #     - name: Copy source code files
  #       uses: actions/checkout@master

  #     - name: Show files and start docker
  #       run: |
  #         whoami
  #         ls
  #         docker-compose up -d
  #         docker ps

  # This job is triggered after the trufflehog job, runs Snyk to check for vulnerabilities in the Docker image, and sends a notification to Discord
  # The notification includes a link to the Snyk report
  SCA-Snyk:
    runs-on: ubuntu-latest
    needs: [trufflehog]
    steps:
      - uses: actions/checkout@v3
      - name: Build a Docker image
        run: docker build -t assignment1:latest .
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{secrets.SNYK_KEY}}
        with:
          image: assignment1:latest
          args: --file=Dockerfile --serif-file-output=snyk.sarif
      - name: save report as pipeline artifact
        id: upload_snyk_report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sca.sarif
          path: snyk.sarif

      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{github.repository}}
          avatar-url: https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/batman_hero_avatar_comics-512.png
          embed-title: "Snyk SCA scan completed. Check the report for vulnerabilities."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "Snyk SARIF report is available. [Download SARIF Report](${{ steps.upload_snyk_report.outputs.artifact-url }})"
          embed-author-name: "${{ github.triggering_actor }}"
          thread-id: "1226943908676632756"

  # This job is triggered after the trufflehog job, runs Semgrep to check for vulnerabilities in the source code, and sends a notification to Discord
  # The notification includes a link to the Semgrep report
  SAST-Semgrep:
    runs-on: ubuntu-latest
    needs: [trufflehog]
    container:
      image: returntocorp/semgrep

    steps:
      - name: clone application source code
        uses: actions/checkout@v3

      - name: full semgrep scan
        run: |
          semgrep \
          --sarif --output semgrep-sast.sarif \
          --metrics=off \
          --config="p/default"

      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v4
        id: upload_semgrep_report
        with:
          name: semgrep-sast.sarif
          path: semgrep-sast.sarif

      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{github.repository}}
          avatar-url: https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/batman_hero_avatar_comics-512.png
          embed-title: "Semgrep SAST scan completed. Check the report for vulnerabilities."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "Semgrep SARIF report is available. [Download SARIF Report](${{ steps.upload_semgrep_report.outputs.artifact-url }})"
          embed-author-name: "${{ github.triggering_actor }}"
          thread-id: "1226943908676632756"

  # This job is triggered first and runs Trufflehog to check for secrets in the source code
  trufflehog:
    runs-on: ubuntu-latest
    needs: [Discord-Begin]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified

  # This job is triggered after the SCA-Snyk and SAST-Semgrep jobs, builds and pushes the Docker image to Docker Hub, and sends a notification to Discord
  build-and-push:
    runs-on: ubuntu-latest
    needs: [SAST-Semgrep, SCA-Snyk]
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/itas276owasp:latest

  # This job is triggered after the build-and-push job, sends a notification to Discord indicating that the pipeline has completed
  discord-end:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{github.repository}}
          avatar-url: https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/batman_hero_avatar_comics-512.png
          embed-title: "Security Pipeline jobs are completed..."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"
          thread-id: "1226943908676632756"
